### ISSUE TITLE
error when running program

### ISSUE THREAD

**Issue by Denybarros** [hritik25/Dynamic-CNN-for-Modelling-Sentences#1]
when I do a running program there are a few exceptions that occur:

1. _SyntaxError: invalid syntax_ on improvisedLayer.py at line 91, this is because there is no comma.

2. then I got an error at _W = lasagne.init.GlorotUniform (), b = lasagne.init.constant (0)_ AttributeError:    'module' object has no attribute 'constant' 

3.  _W = lasagne.init.GlorotUniform(), b = lasagne.init.constant(0)_, NameError: name 'lasagne' is not defined

how to fix it?

**Comment by hritik25** [comment]
Hey, sorry for the inconvenience and thanks for pointing it out. I have updated the erroneous code. Please run it and let me know if there is any bug there.
