### ISSUE TITLE
Request for further info. 

### ISSUE THREAD

**Issue by naveenjafer** [hritik25/Dynamic-CNN-for-Modelling-Sentences#5]
Hi Hritik, do you have a set of instructions for training and getting predictions and abstract as to what framework is used in the same. The current README file doesn't have any info. Thank you.

**Comment by hritik25** [comment]
Hi Naveen, I'm sorry for not putting up a detailed description. Please
refer to this implementation which I referred to while implementing:
https://github.com/FredericGodin/DynamicCNN

Thanks,

Hritik Jain,
Cognition Lab,
Centre for Neuroscience,
IISc Bangalore, 560012
